Repository TidyBee/tidybee-hub, pull requests merged in 2024-03, with the labels that each got.

#40 Status handler v2
  ApiGateway/Controllers/GatewayController.cs
  Auth/Controllers/AOTHController.cs
  Auth/Models/AothBodyModel.cs
  Auth/Program.cs
  Auth/Repository/AgentRepository.cs
  Auth/Services/StatusHandlerService.cs
  Auth/appsettings.Development.json
Labels: enhancement

#44 Build and push an container image to the repository container registry
  .devcontainer/devcontainer.json
  .github/workflows/docker.yaml
  ApiGateway/Dockerfile
  Auth/Dockerfile
  DataProcessing/Dockerfile
Labels: enhancement

#45 Update README
  README.md
Labels: documentation

#42 41 implementation of predefined gateway routes for front end widgets
  Auth/appsettings.Development.json
  DataProcessing/Controllers/WidgetsProcessingController.cs
  DataProcessing/DataProcessing.csproj
Labels: front
